@Api_HostAddress = http://localhost:5260

POST {{Api_HostAddress}}/api/users
Content-Type: application/json

{
  "name": "Joao Victor",
  "email": "joao@email.com",
  "password": "senha@123"
}

###

# Response
